"""add description to products

Revision ID: 501052f955f0
Revises: 537499d67abd
Create Date: 2020-10-07 10:45:20.477941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501052f955f0'
down_revision = '537499d67abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
