"""create products

Revision ID: 537499d67abd
Revises: 
Create Date: 2020-10-07 10:00:56.796856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537499d67abd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
